spring:
  application:
    name: "gatewayserver"
  config:
    import: optional:configserver:http://localhost:8084/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "TL Bank gatewayserver Application"
    version: "1.0.0"