services:
  accountsdb:
    container_name: accountsdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    container_name: cardsdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    container_name: loansdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "m0ewth/configserver-service:v1.0.1"
    container_name: configserver-ms
    ports:
      - "8084:8084"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8084/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "m0ewth/eurekaserver-service:v1.0.2"
    container_name: eurekaserver-ms
    ports:
      - "8085:8085"
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8085/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "m0ewth/accounts-service:v1.0.3"
    container_name: accounts-ms
    ports:
      - "8081:8081"
    depends_on:
      accountsdb:
        condition: service_healthy
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    extends:
      file: common-config.yml
      service: microservice-clientConfigServer-config

  cards:
    image: "m0ewth/cards-service:v1.0.3"
    container_name: cards-ms
    ports:
      - "8082:8082"
    depends_on:
      cardsdb:
        condition: service_healthy
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8082/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-clientConfigServer-config

  loans:
    image: "m0ewth/loans-service:v1.0.3"
    container_name: loans-ms
    ports:
      - "8083:8083"
    depends_on:
      loansdb:
        condition: service_healthy
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8083/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    extends:
      file: common-config.yml
      service: microservice-clientConfigServer-config

  gatewayserver:
    image: "m0ewth/gatewayserver-service:v1.0.0"
    container_name: gatewayserver-ms
    ports:
      - "8080:8080"
    depends_on:
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-clientConfigServer-config

networks:
  tl_bank:
    driver: "bridge"