server:
  port: 8084

spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
        git:
          uri: https://github.com/ThanhLiemm/microservices-bank-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: trueV
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"